[workspace]
members = ["sdk", "sdk-macro", "types"]
resolver = "2"

[workspace.package]
version = "0.11.0"
edition = "2024"
license = "MIT"
homepage = "https://www.omnity.network/"
repository = "https://github.com/octopus-network/ree-exchange-sdk"
description = "REE exchange rust SDK."
